name: Test usage of env vars

on:
  push:
    branches: ["*"]
  release:
    types:
      - created

jobs:
  test-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: thiedebr/fake-image
          tags: |
            type=sha,format=long
            type=raw,value=${{ github.event.release.tag_name }}
            type=raw,value=latest

      - name: Spit out env vars
        env:
          DOCKER_META_TAGS: ${{ steps.meta.outputs.tags }}
          DOCKER_META_LABELS: ${{ steps.meta.outputs.labels }}
        run: |
          echo "DOCKER_META_TAGS = '${DOCKER_META_TAGS}'"
          echo "DOCKER_META_LABELS = '${DOCKER_META_LABELS}'"
